apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: zih9pkyps-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c8a82b8c19.nbno.p3.openshiftapps.com/rhtap/rhtap-qe:7481242e89246c4bac3550bde49b725d4f649491@sha256:9ac656ab1f702260f17dfe9ecd5ac2e8c51e9385704d1270733570e6f2ecbea2
        name: container-image  
